# My shit
book:
  coverpage: true
  contactpage: true
  index: false
  leftpage: "dotgrid"
  rightpage: "blank"
  diameter: 0.1875
  units: "in"
  pageheight: 8
  pagewidth: 5.25
quantity: 10
lineheight: 0.1875
pageheight: 8
pagewidth: 5.25


# Default Options
title: 'Pages - The Pieces of a Notebook'
email: ryan.horricks@gmail.com
description: >
  Make half-size notebooks using a consumer-grade printer.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
github_username: codekane


# SEO
#image: /assets/images/open_graph_image.png
gaCode: # UA-XXXXXXXX-XX

# Build settings
markdown: kramdown
incremental: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

defaults:
  -
      scope:
        path: "/preset/"
      values:
       layout: "preview"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - flightdeck.manifest.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package-lock.json # for those that use npm
  - package.json
  - README.md
  - vendor
  - yarn.lock # for those that use yarn
